runtime: java16
env: standard
runtime_config:
  jdk: openjdk16
#handlers:
#  - url: /.*
#    script: this field is required, but ignored
#env_variables:
#  SPRING_PROFILES_ACTIVE: "production"
#
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1
